### ISSUE TITLE
Swift 4 Support?

### ISSUE THREAD

**Issue by WillBishop** [chrisdhaan/CDMarkdownKit#5]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with what info we expect. You can delete those lines once you've filled in the info.
>
> Per our [*CONTRIBUTING guidelines](https://github.com/chrisdhaan/CDMarkdownKit/blob/master/CONTRIBUTING.md), we use GitHub for
> bugs and feature requests, not general support. Other issues should be opened on Stack Overflow with the tag `cdmarkdownkit`.
>
> Please remove this line and everything above it before submitting.

* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/chrisdhaan/CDMarkdownKit/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ Please replace this with what you did.  

I expected Swift 4 to work

ℹ Please replace this with what you expected to happen.  

It crashed with numerous errors, some fixable, others not.

ℹ Please replace this with of what happened instead.  

## CDMarkdownKit Environment

**CDMarkdownKit version:**  
**Xcode version:**  
**Swift version:**  
**Platform(s) running CDMarkdownKit:**  
**macOS version running Xcode:**

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by tklucher** [comment]
@WillBishop Swift 4 is not currently supported yet but should be soon as per [this conversation](https://github.com/chrisdhaan/CDMarkdownKit/pull/1).

If you would like to play with the code right now that pull request is swift 4 compatible and has no API changes so it would be a drop in change back to this repo when the swift 4 version which is placed to be 1.0.0 is released. The render will be slightly different than the release version as that developer of that pull also changed paragraph styles and those may not be implemented for a bit. That is a currently feature request [here](https://github.com/chrisdhaan/CDMarkdownKit/issues/4) that will be reviewed by @chrisdhaan over time.

**Comment by chrisdhaan** [comment]
@WillBishop I'm working to get this project up to date for Swift 4 very soon. I've unfortunately been very busy as of late and have not been able to donate as much time as I'd like to development. I hope to have another update out after this weekend.

**Comment by WillBishop** [comment]
Good luck! It’s the only markdown kit that supports watchOS so I’m looking forward to the update!

**Comment by WillBishop** [comment]
Actually just checked the pull request and it doesn't have watchos support seemingly

**Comment by chrisdhaan** [comment]
@WillBishop started working on #4 which is the last thing I'd like to finish before releasing `1.0.0`. Should be done within the next couple of days. After that I'll update to Swift 4 and push `1.1.0`. Hopefully within a weeks time your needs will be met.

**Comment by WillBishop** [comment]
Fantastic! Appreciate the work!

**Comment by chrisdhaan** [comment]
@WillBishop I've finished #4 and also fixed some formatting on other markdown elements. The last thing I wanted to do was add link selection support to the UILabel element before releasing `1.0.0`. But if Swift4 is holding you up from release. I can prioritize Swift4 ahead of the UILabel work and just release `1.0.0` now and update to Swift4 with `1.1.0` tomorrow. Let me know whats best for you.

**Comment by WillBishop** [comment]
Whatever works best for you man,

I’ve got a Swift 4 fork anyway, official support would be preferred but no need to prioritise it!

**Comment by FelixII** [comment]
Hi @chrisdhaan,

I've started using and integrating this library into my own project. Really like it so far. What's the current status of the 1.0/Swift 4 release?

Thanks and keep up the good work!

**Comment by chrisdhaan** [comment]
@FelixII apologies on the delay. I was out of the country for the past two weeks and did not have a computer with me. I plan on getting back to working on the project this upcoming week.

**Comment by WillBishop** [comment]
I’m not Felix, but no problem Chris!

**Comment by FelixII** [comment]
That's good news. Take your time.

**Comment by robotsquidward** [comment]
Love this lib, but struggling to do a Swift 4 convert in my project in the 0.9 release.  Any update?

**Comment by chrisdhaan** [comment]
Had a break through over the weekend with the final functionality I was trying to get in before updated to Swift 4. Should hopefully see it sometime around Monday or Tuesday @robotsquidward

**Comment by robotsquidward** [comment]
Thanks @chrisdhaan!  You'll save me from some regex madness trying to create my own with a standard UITextView 🤓

**Comment by chrisdhaan** [comment]
Added Swift 4 support with version`1.1.0`. @robotsquidward @FelixII @WillBishop @tklucher please let me know if you run into any issues. If everything is working fine I'll close out this issue.

**Comment by FelixII** [comment]
Thanks for your work, @chrisdhaan. I've noticed that the `SWIFT_VERSION` property in your project settings is still set to `3.0`. As soon as I change it to `4.0` and build the project, I receive the following error in several places:

`Cannot convert value of type '[String : AnyObject]' to expected argument type '[NSAttributedStringKey : Any]'`

Swift 4 changed the key type of attribute dictionaries from `String` to `NSAttributedStringKey`. However `CDMarkdownStyle` still uses `String` as the key type for its `attributes` property.

Is there a commit missing?

**Comment by chrisdhaan** [comment]
@FelixII this is a good find. Thanks for pointing it out. I'm surprised the CI didn't generate this error nor did Xcode while I was making the update. I'll fix it today.

**Comment by FelixII** [comment]
Xcode displays compiler errors and warnings based on the selected Swift version. Set it to 4.0 in your project settings and you should see the errors.

**Comment by FelixII** [comment]
CDMarkdownKit compiles fine now with Swift 4. Thanks again, @chrisdhaan !

**Comment by FelixII** [comment]
I've discovered two more compiler issues with the macOS target and create a PR: #10

**Comment by darrinhenein** [comment]
> Xcode displays compiler errors and warnings based on the selected Swift version. Set the "Swift Language Version" to "Swift 4.1" in your project settings and you should see the errors.

I see numerous compilation errors with either Swift 4.1 or 4.2 as well.

**Comment by FelixII** [comment]
@darrinhenein Please make sure that you have fetched the latest commit from this repo. If you're using CocoaPods, you have to specify the repo explicitly because the tag is a few commits behind:

`pod 'CDMarkdownKit', :git => 'https://github.com/chrisdhaan/CDMarkdownKit'`

**Comment by chrisdhaan** [comment]
@darrinhenein I'll be releasing a new tag in the next couple of days if you'd rather wait for that.

**Comment by darrinhenein** [comment]
Thanks, pointing to the github repo worked with Swift 4.2! My parsed markdown is showing up in the CDMarkdownTextView as html strings (`<p>Hello <strong>World</strong></p>`) but it's a start :)

**Comment by edwardmp** [comment]
@chrisdhaan 

can you release a new tag? thanks!

**Comment by chrisdhaan** [comment]
@edwardmp I pushed up my last commits for the new version today. The `CHANGELOG.md` and once the Travis CI build finishes I'll release a new tag.

**Comment by edwardmp** [comment]
@chrisdhaan 

Great job, thanks!

**Comment by chrisdhaan** [comment]
Version `1.2.0` has been released. I'll keep this Issue open for a while in case other problems arise with Swift 4 compatibility.

**Comment by FelixII** [comment]
@edwardmp If you're using UITextView, take a look at https://developer.apple.com/documentation/uikit/uitextviewdelegate/1649337-textview

**Comment by chrisdhaan** [comment]
Version `1.2.1` is being released to with Swift `4.2` compatibility and fixes issues with `4.0` compilation errors. Closing issue.
